CREATE USER kalkal WITH PASSWORD 'sang@830139'
SET timezone = 'Asia/Seoul';
GRANT CONNECT ON DATABASE kalkal_db TO kalkal;
GRANT USAGE ON SCHEMA humor TO kalkal;
GRANT USAGE ON SCHEMA quote TO kalkal;
GRANT SELECT,
    INSERT,
    UPDATE,
    DELETE ON ALL TABLES IN SCHEMA humor TO kalkal;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA humor TO kalkal;
GRANT SELECT,
    INSERT,
    UPDATE,
    DELETE ON ALL TABLES IN SCHEMA quote TO kalkal;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA quote TO kalkal;